version: '3'

services:
#  app:
#    build:
#      context: ..
#      dockerfile: .devcontainer/Dockerfile
#
#    volumes:
#      - ../..:/workspaces:cached
#
#    networks:
#      ktg-net:
#
#    environment:
#      - SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    networks:
      ktg-net:

#  db:
#    image: postgres:15.1
#    # restart: unless-stopped
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_DB: postgres
#      POSTGRES_PASSWORD: postgres
#
#    networks:
#      ktg-net:

networks:
  ktg-net:

volumes:
  postgres-data: