default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>


local:
    <<: *default
    database: desafio_full_stack
    username: postgres
    password: postgres
    host: localhost
    port: 5432

test:
  <<: *default
  database: desafio_full_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host:  <%= ENV['POSTGRES_HOST'] %>
  port:  <%= ENV['POSTGRES_PORT'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
